version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: uas_reporting
      POSTGRES_USER: uas_user
      POSTGRES_PASSWORD: uas_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uas_user -d uas_reporting"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://uas_user:uas_password@postgres:5432/uas_reporting
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend
    restart: unless-stopped

  # React Frontend
  frontend:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm install && npm start"
    depends_on:
      - backend
    restart: unless-stopped

  # pgAdmin Database Management
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@uasreporting.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data: 